#lang racket

(require (for-syntax syntax/parse))
(require racket/mutable-treelist)
(require threading)
(require "ast.rkt")
(require "ast-utils.rkt")

(define-syntax (define-attribute stx)
  (syntax-parse stx
    [(_ name:id arg:id ...)
     #`(define (name arg ...)
         (~> (ast-attribute-node
              (mutable-treelist)
              (~> 'name symbol->string underscorize)
              (list arg ...))
             append-ast-node!))]))

(define-attribute random-placement)
(define-attribute grouped-by-team)
(define-attribute direct-placement)
(define-attribute nomad-resources)
(define-attribute force-nomad-treaty)
(define-attribute behavior-version version-number)
(define-attribute override-map-size side-length)
(define-attribute set-gaia-civilization civ-number)
(define-attribute ai-info-map-type map-type is-nomad is-michi show-type)
(define-attribute effect-amount effect-type type attribute-type amount)
(define-attribute effect-percent effect-type type attribute-type percentage)
(define-attribute guard-state object-type resource-type resource-delta flags)
(define-attribute terrain-state mode parameter1 parameter2 flags)
(define-attribute weather-type precipitation-style live-color fog-color water-direction)
(define-attribute water-definition type)
(define-attribute base-terrain terrain-type)
(define-attribute base-layer terrain-type)
(define-attribute enable-waves show-waves)
(define-attribute terrain-type terrain)
(define-attribute land-percent percentage)
(define-attribute number-of-tiles amount)
(define-attribute base-size radius)
(define-attribute generate-mode mode)
(define-attribute circle-radius radius-percentage variance)
(define-attribute left-border percent)
(define-attribute right-border percent)
(define-attribute top-border percent)
(define-attribute bottom-border percent)
(define-attribute border-fuzziness percent)
(define-attribute clumping-factor factor)
(define-attribute land-conformity percentage)
(define-attribute base-elevation height)
(define-attribute zone zone-number)
(define-attribute set-zone-by-team)
(define-attribute set-zone-randomly)
(define-attribute other-zone-avoidance-distance tiles)
(define-attribute land-id identifier)
(define-attribute land-position percentage-x percentage-y)
(define-attribute assign-to-player player-number)
(define-attribute assign-to assign-target number mode flags)
(define-attribute min-placement-distance tiles)
(define-attribute number-of-clumps amount)
(define-attribute set-scale-by-size)
(define-attribute set-scale-by-groups)
(define-attribute spacing amount)
(define-attribute enable-balanced-elevation)
(define-attribute cliff-type type)
(define-attribute min-number-of-cliffs amount)
(define-attribute max-number-of-cliffs amount)
(define-attribute min-length-of-cliff length)
(define-attribute max-length-of-cliff length)
(define-attribute cliff-curliness percentage)
(define-attribute min-distance-cliffs distance)
(define-attribute min-terrain-distance distance)
(define-attribute set-circular-base)
(define-attribute color-correction color-correction-type)
(define-attribute beach-terrain terrain-type)
(define-attribute terrain-mask layer)
(define-attribute spacing-to-other-terrain-types distance)
(define-attribute spacing-to-specific-terrain type distance)
(define-attribute set-flat-terrain-only)
(define-attribute set-avoid-player-start-areas distance)
(define-attribute height-limits min max)
(define-attribute accumulate-connections)
(define-attribute default-terrain-replacement terrain-type)
(define-attribute replace-terrain terrain-type-old terrain-type-new)
(define-attribute terrain-cost terrain-type cost)
(define-attribute terrain-size terrain-type radius cost)
(define-attribute create-actor-area x y id radius)
(define-attribute number-of-objects amount)
(define-attribute number-of-groups amount)
(define-attribute group-variance amount)
(define-attribute group-placement-radius radius)
(define-attribute set-tight-grouping)
(define-attribute set-loose-grouping)
(define-attribute min-connected-tiles amount)
(define-attribute resource-delta amount)
(define-attribute second-object type)
(define-attribute set-scaling-to-map-size)
(define-attribute set-scaling-to-player-number)
(define-attribute set-place-for-every-player)
(define-attribute place-on-specific-land-id id)
(define-attribute avoid-other-land-zones n)
(define-attribute generate-for-first-land-only)
(define-attribute set-gaia-object-only)
(define-attribute set-gaia-unconvertible)
(define-attribute set-building-capturable)
(define-attribute make-indestructible)
(define-attribute min-distance-to-players distance)
(define-attribute max-distance-to-players distance)
(define-attribute set-circular-placement)
(define-attribute terrain-to-place-on type)
(define-attribute layer-to-place-on type)
(define-attribute ignore-terrain-restrictions)
(define-attribute max-distance-to-other-zones distance)
(define-attribute place-on-forest-zone)
(define-attribute avoid-forest-zone distance)
(define-attribute avoid-cliff-zone distance)
(define-attribute min-distance-to-map-edge distance)
(define-attribute min-distance-group-placement distance)
(define-attribute temp-min-distance-group-placement distance)
(define-attribute find-closest)
(define-attribute find-closest-to-map-center)
(define-attribute find-closest-to-map-edge)
(define-attribute require-path deviation)
(define-attribute force-placement)
(define-attribute actor-area id)
(define-attribute actor-area-radius radius)
(define-attribute override-actor-radius-if-required)
(define-attribute actor-area-to-place-in id)
(define-attribute avoid-actor-area id)
(define-attribute avoid-all-actor-areas)
(define-attribute enable-tile-shuffling)
(define-attribute set-facet facet-number)
(define-attribute match-player-civ)
(define-attribute add-object object-type percentace)

(provide (except-out (all-defined-out) define-attribute))
